using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;

namespace Vortex.Unity.StateAxisSystem.EditorTools
{
    /// <summary>
    /// Генератор C#-кода для StateAxis-наследников. Полная регенерация без маркеров —
    /// файл всегда перезатирается целиком. Содержит шапку <c>&lt;auto-generated&gt;</c>
    /// с инструкцией не редактировать вручную и встроенный nested-класс <c>EditorMenu</c>
    /// под <c>#if UNITY_EDITOR</c> с пунктом <c>Vortex/StateAxis/{AxisName}</c>.
    /// </summary>
    internal static class StateAxisCodeGenerator
    {
        private static readonly Regex ValidIdentifier = new(@"^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);
        private static readonly Regex ValidNamespace = new(@"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)*$", RegexOptions.Compiled);

        public static bool IsValidIdentifier(string s) =>
            !string.IsNullOrEmpty(s) && ValidIdentifier.IsMatch(s);

        public static bool IsValidNamespace(string s) =>
            !string.IsNullOrEmpty(s) && ValidNamespace.IsMatch(s);

        /// <summary>Удаляет точки из строки. Используется для live-чистки в инспекторе.</summary>
        public static string StripDots(string s) =>
            string.IsNullOrEmpty(s) ? s : s.Replace(".", string.Empty);

        public static string Generate(string axisName, string targetNamespace, IReadOnlyList<string> keys)
        {
            var sb = new StringBuilder();

            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//   Этот файл сгенерирован Vortex StateAxis Code Generator.");
            sb.AppendLine("//   НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ. Все ручные изменения будут потеряны при следующей");
            sb.AppendLine("//   регенерации. Для изменения набора значений отредактируйте парный пресет");
            sb.AppendLine($"//   ({axisName}.asset) в инспекторе и нажмите Save.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("//------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Vortex.Core.StateAxisSystem.Abstractions;");
            sb.AppendLine();
            sb.AppendLine($"namespace {targetNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {axisName} : StateAxis");
            sb.AppendLine("    {");

            for (int i = 0; i < keys.Count; i++)
                sb.AppendLine($"        public static readonly {axisName} {keys[i]} = new(nameof({keys[i]}), {i});");

            sb.AppendLine();
            sb.AppendLine($"        public static IReadOnlyList<{axisName}> All => GetAll<{axisName}>();");
            sb.AppendLine();
            sb.AppendLine($"        private {axisName}(string key, int order) : base(key, order) {{ }}");
            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine("        private static class EditorMenu");
            sb.AppendLine("        {");
            sb.AppendLine($"            [UnityEditor.MenuItem(\"Vortex/StateAxis/{axisName}\")]");
            sb.AppendLine("            private static void OpenPreset()");
            sb.AppendLine("            {");
            sb.AppendLine($"                var guids = UnityEditor.AssetDatabase.FindAssets(\"{axisName} t:StateAxisPreset\");");
            sb.AppendLine("                foreach (var guid in guids)");
            sb.AppendLine("                {");
            sb.AppendLine("                    var path = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);");
            sb.AppendLine("                    var preset = UnityEditor.AssetDatabase.LoadAssetAtPath<Vortex.Unity.StateAxisSystem.Presets.StateAxisPreset>(path);");
            sb.AppendLine($"                    if (preset != null && preset.AxisName == \"{axisName}\")");
            sb.AppendLine("                    {");
            sb.AppendLine("                        UnityEditor.Selection.activeObject = preset;");
            sb.AppendLine("                        UnityEditor.EditorGUIUtility.PingObject(preset);");
            sb.AppendLine("                        return;");
            sb.AppendLine("                    }");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}
