#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace Vortex.Unity.Extensions.Editor.Templates
{
    /// <summary>
    /// Контекстное меню для генерации файлов из шаблона ViewForIDataStorage.vtp.
    /// Auto-generated by VtpTemplateCreatorWindow.
    /// </summary>
    public static class ViewForIDataStorageTemplateMenu
    {
        private const string TemplateName = "ViewForIDataStorage.vtp";
        private const string MenuClassName = "ViewForIDataStorageTemplateMenu";

        private static readonly Dictionary<string, string> Substitutions = new()
        {
        };

        [MenuItem("Assets/Create/Vortex Templates/View for IDataStorage", false, 80)]
        private static void Generate()
        {
            string outputFolder = GetSelectedFolderPath();

            if (string.IsNullOrEmpty(outputFolder))
            {
                EditorUtility.DisplayDialog(
                    "Ошибка",
                    "Не удалось определить папку. Выберите папку в окне Project.",
                    "OK"
                );
                return;
            }

            string templatePath = GetTemplatePath();

            if (string.IsNullOrEmpty(templatePath) || !File.Exists(templatePath))
            {
                EditorUtility.DisplayDialog(
                    "Ошибка",
                    $"Шаблон '{TemplateName}' не найден рядом с {MenuClassName}.cs",
                    "OK"
                );
                return;
            }

            VtpGeneratorWindow.ShowWindow(templatePath, outputFolder, Substitutions);
        }

        [MenuItem("Assets/Create/Vortex Templates/ViewForIDataStorage", true)]
        private static bool GenerateValidation()
        {
            return !string.IsNullOrEmpty(GetSelectedFolderPath());
        }

        private static string GetSelectedFolderPath()
        {
            foreach (Object obj in Selection.GetFiltered<Object>(SelectionMode.Assets))
            {
                string path = AssetDatabase.GetAssetPath(obj);

                if (string.IsNullOrEmpty(path))
                    continue;

                if (AssetDatabase.IsValidFolder(path))
                    return path;

                string directory = Path.GetDirectoryName(path);
                if (!string.IsNullOrEmpty(directory))
                    return directory;
            }

            return null;
        }

        private static string GetTemplatePath()
        {
            string[] guids = AssetDatabase.FindAssets($"t:Script {MenuClassName}");

            foreach (string guid in guids)
            {
                string scriptPath = AssetDatabase.GUIDToAssetPath(guid);

                if (!scriptPath.EndsWith($"{MenuClassName}.cs"))
                    continue;

                string scriptFolder = Path.GetDirectoryName(scriptPath);
                string templatePath = Path.Combine(scriptFolder, TemplateName);

                return templatePath;
            }

            return null;
        }
    }
}
#endif